# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import itertools
import numpy as np


def random_matrix(long):
    """
    The function generates long x long array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size=(long, long))
    print(matrix)
    return matrix


def list_permutations(long):
    """
    This function generates permutations for index in the new string
    """
    t = np.arange(long)
    t = list(itertools.permutations(t, long))
    return t


def product_count(matrix, list_permutation, long):
    """
    This function multiplies the elements of the matrix
    """
    k = []
    for y in list_permutation:
        count = 0
        for j in range(len(y)):
            for i in range(j+1, len(y)):
                if y[j] > y[i]:
                    count += 1
        if count % 2 == 0:
            sign = 1
        else:
            sign = -1
        for j in range(long):
            sign *= matrix[j][y[j]]
        k.append(sign)
    return k


def summary(prod_count):
    b = 0
    for i in range(len(prod_count)):
        b = b + prod_count[i]
    return b


while True:
    try:
        dim = int(input("Enter the number of numbers you plan to use less than 10:"))
    except:
        print("An incorrect type of the variable k was entered.")
    r = summary(product_count(random_matrix(dim), list_permutations(dim), dim))
    print(r)
    print("If you want to exit, enter 'exit', and if you want to continue, enter anything")
    a = input()
    if a == 'exit':
        break


[[8 7 1 8 2]
 [2 0 5 6 5]
 [1 9 2 9 9]
 [9 3 4 3 7]
 [5 4 1 3 8]]
[[8 7 1 8 2]
 [2 0 5 6 5]
 [1 9 2 9 9]
 [9 3 4 3 7]
 [5 4 1 3 8]]
8817.999999999998
8818
If you want to exit, enter 'exit', and if you want to continue, enter anything
